package gtclassic.common;

import ic2.core.platform.lang.components.base.LangComponentHolder;
import ic2.core.platform.lang.components.base.LangComponentHolder.LocaleBlockComp;
import ic2.core.platform.lang.components.base.LocaleComp;

public class GTLang {

	/** Block/Tile References **/
	public static final LocaleComp AUTOCRAFTER = new LangComponentHolder.LocaleBlockComp("tile.gtclassic.autocrafter");
	public static final LocaleComp CHARGE_O_MAT = new LangComponentHolder.LocaleBlockComp("tile.gtclassic.chargeomat");
	public static final LocaleComp COMPUTER_CUBE = new LangComponentHolder.LocaleBlockComp("tile.gtclassic.computercube");
	public static final LocaleComp INDUSTRIAL_CENTRIFUGE = new LangComponentHolder.LocaleBlockComp("tile.gtclassic.industrialcentrifuge");
	public static final LocaleComp MATTER_FAB = new LangComponentHolder.LocaleBlockComp("tile.gtclassic.matterfabricator");
	public static final LocaleComp UUM_ASSEMBLER = new LangComponentHolder.LocaleBlockComp("tile.gtclassic.uumassembler");
	public static final LocaleComp ECHOTRON = new LangComponentHolder.LocaleBlockComp("tile.gtclassic.echotronblock");
	public static final LocaleComp DIGITAL_CHEST = new LangComponentHolder.LocaleBlockComp("tile.gtclassic.digitalchest");
	public static final LocaleComp QUANTUM_CHEST = new LangComponentHolder.LocaleBlockComp("tile.gtclassic.quantumchest");
	public static final LocaleComp QUANTUM_TANK = new LangComponentHolder.LocaleBlockComp("tile.gtclassic.quantumtank");
	public static final LocaleComp PLAYER_DETECTOR = new LangComponentHolder.LocaleBlockComp("tile.gtclassic.playerdetector");
	public static final LocaleComp DISASSEMBLER = new LangComponentHolder.LocaleBlockComp("tile.gtclassic.disassembler");
	public static final LocaleComp MOB_REPELLER = new LangComponentHolder.LocaleBlockComp("tile.gtclassic.mobrepeller");
	public static final LocaleComp ENERGY_TRANSMITTER = new LangComponentHolder.LocaleBlockComp("tile.gtclassic.energytransmitter");
	public static final LocaleComp BEDROCK_MINER = new LangComponentHolder.LocaleBlockComp("tile.gtclassic.bedrockminer");
	public static final LocaleComp FUSION_REACTOR = new LangComponentHolder.LocaleBlockComp("tile.gtclassic.fusionreactor");
	public static final LocaleComp LIGHTNING_ROD = new LangComponentHolder.LocaleBlockComp("tile.gtclassic.lightningrod");
	public static final LocaleComp CHARCOAL_PIT = new LangComponentHolder.LocaleBlockComp("tile.gtclassic.charcoalpit");
	public static final LocaleComp DRAGON_EGG_ENERGY_SIPHON = new LangComponentHolder.LocaleBlockComp("tile.gtclassic.dragoneggenergysiphon");
	public static final LocaleComp MAGIC_ENERGY_CONVERTER = new LangComponentHolder.LocaleBlockComp("tile.gtclassic.magicenergyconverter");
	public static final LocaleComp MAGIC_ENERGY_ABSORBER = new LangComponentHolder.LocaleBlockComp("tile.gtclassic.magicenergyabsorber");
	public static final LocaleComp LESU = new LangComponentHolder.LocaleBlockComp("tile.gtclassic.lesu");
	public static final LocaleComp AESU = new LangComponentHolder.LocaleBlockComp("tile.gtclassic.aesu");
	public static final LocaleComp IDSU = new LangComponentHolder.LocaleBlockComp("tile.gtclassic.idsu");
	public static final LocaleComp TESSERACT_MASTER = new LangComponentHolder.LocaleBlockComp("tile.gtclassic.tesseractmaster");
	public static final LocaleComp TESSERACT_SLAVE = new LangComponentHolder.LocaleBlockComp("tile.gtclassic.tesseractslave");
	public static final LocaleComp REDSTONE_TRANSMITTER = new LangComponentHolder.LocaleBlockComp("tile.gtclassic.redstonetransmitter");
	public static final LocaleComp REDSTONE_RECEIVER = new LangComponentHolder.LocaleBlockComp("tile.gtclassic.redstonereceiver");
	public static final LocaleComp SUPERCONDENSATOR = new LangComponentHolder.LocaleBlockComp("tile.gtclassic.supercondensator");
	public static final LocaleComp BLOCK_EXTENDER = new LangComponentHolder.LocaleBlockComp("tile.gtclassic.blockextender");
	public static final LocaleComp SUPERCONDUCTORCABLE = new LangComponentHolder.LocaleBlockComp("tile.gtclassic.superconductorcable");
	public static final LocaleComp DATACABLE = new LangComponentHolder.LocaleBlockComp("tile.gtclassic.datacable");
	public static final LocaleComp WORKTABLE = new LangComponentHolder.LocaleBlockComp("tile.gtclassic.worktable");
	public static final LocaleComp CABINET = new LangComponentHolder.LocaleBlockComp("tile.gtclassic.cabinet");
	public static final LocaleComp DRUM = new LangComponentHolder.LocaleBlockComp("tile.gtclassic.drum");
	public static final LocaleComp BATTERYBLOCK_LV = new LangComponentHolder.LocaleBlockComp("tile.gtclassic.batteryblocklv");
	public static final LocaleComp TRANSLOCATOR = new LangComponentHolder.LocaleBlockComp("tile.gtclassic.translocator");
	public static final LocaleComp TRANSLOCATOR_FLUID = new LangComponentHolder.LocaleBlockComp("tile.gtclassic.translocatorfluid");
	public static final LocaleComp TYPE_FILTER = new LangComponentHolder.LocaleBlockComp("tile.gtclassic.typefilter");
	public static final LocaleComp ITEM_FILTER = new LangComponentHolder.LocaleBlockComp("tile.gtclassic.itemfilter");
	public static final LocaleComp ROCK_BREAKER = new LangComponentHolder.LocaleBlockComp("tile.gtclassic.rockbreaker");
	public static final LocaleComp BUFFER_LARGE = new LangComponentHolder.LocaleBlockComp("tile.gtclassic.bufferlarge");
	public static final LocaleComp BUFFER_SMALL = new LangComponentHolder.LocaleBlockComp("tile.gtclassic.buffersmall");
	public static final LocaleComp BUFFER_FLUID = new LangComponentHolder.LocaleBlockComp("tile.gtclassic.bufferfluid");
	public static final LocaleComp ORE_BEDROCK = new LocaleBlockComp("tile.gtclassic.oreBedrock");
	public static final LocaleComp TEST = new LocaleBlockComp("tile.gtclassic.test");
	/** Buttons **/
	public static final String BUTTON_TEST = "button.gtclassic.test";
	public static final String BUTTON_SORT = "button.gtclassic.sort";
	public static final String BUTTON_NOPOWER = "button.gtclassic.nopower";
	public static final String BUTTON_STRUCUTURE_TRUE = "button.gtclassic.structure0";
	public static final String BUTTON_STRUCUTURE_FALSE = "button.gtclassic.structure1";
	public static final String BUTTON_DIGITALCHEST_UPLOAD = "button.gtclassic.digitalchest0";
	public static final String BUTTON_DIGITALCHEST_DOWNLOAD = "button.gtclassic.digitalchest1";
	public static final String BUTTON_MAGICABSORBER_PLAYER = "button.gtclassic.magicabsorber0";
	public static final String BUTTON_MAGICABSORBER_POTION = "button.gtclassic.magicabsorber1";
	public static final String BUTTON_MAGICABSORBER_PORTAL = "button.gtclassic.magicabsorber2";
	public static final String BUTTON_MAGICABSORBER_WARNING = "button.gtclassic.magicabsorber3";
	public static final String BUTTON_UUM_CLEAR = "button.gtclassic.uum0";
	public static final String BUTTON_UUM_SCAN = "button.gtclassic.uum1";
	public static final String BUTTON_UUM_CLEARTARGET = "button.gtclassic.uum2";
	public static final String BUTTON_WORKTABLE_SHIFTPLAYER = "button.gtclassic.worktable0";
	public static final String BUTTON_WORKTABLE_SHIFTINV = "button.gtclassic.worktable1";
	public static final String BUTTON_BUFFER_ENERGY = "button.gtclassic.buffer0";
	public static final String BUTTON_BUFFER_REDSTONE = "button.gtclassic.buffer1";
	public static final String BUTTON_BUFFER_INVREDSTONE = "button.gtclassic.buffer2";
	public static final String BUTTON_BUFFER_INVFILTER = "button.gtclassic.buffer3";
	public static final String BUTTON_BUFFER_IGNORENBT = "button.gtclassic.buffer4";
	public static final String BUTTON_AESU_ADD64 = "button.gtclassic.aesu0";
	public static final String BUTTON_AESU_ADD1 = "button.gtclassic.aesu1";
	public static final String BUTTON_AESU_SUB1 = "button.gtclassic.aesu2";
	public static final String BUTTON_AESU_SUB64 = "button.gtclassic.aesu3";
	public static final String BUTTON_ROCKBREAKER = "button.gtclassic.rockbreaker";
}
