package gtclassic.util;

import gtclassic.GTClassic;
import gtclassic.items.*;
import gtclassic.items.GTItemDusts.GTItemDustTypes;
import gtclassic.items.GTItemTinyDusts.GTItemTinyDustTypes;
import gtclassic.items.GTItemNuggets.GTItemNuggetTypes;
import gtclassic.items.GTItemMaterials.GTItemMaterialTypes;
import gtclassic.items.GTItemComponents.GTItemComponentTypes;
import gtclassic.items.armor.GTItemLithiumBatpack;
import gtclassic.items.eustorage.GTItemLapotronicEnergyOrb;
import gtclassic.items.eustorage.GTItemLitiumBattery;
import gtclassic.items.tools.GTItemAdvancedChainsaw;
import gtclassic.items.tools.GTItemAdvancedDrill;
import gtclassic.items.tools.GTItemHammerIron;
import net.minecraft.item.Item;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.common.registry.GameRegistry;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;
import net.minecraftforge.registries.IForgeRegistry;

@GameRegistry.ObjectHolder(GTClassic.MODID)
public class GTItems {

    public static final GTItemCreditDoge creditDoge = new GTItemCreditDoge();
	public static final GTItemCreditAlk creditAlk = new GTItemCreditAlk();
	public static final GTItemHammerIron hammerIron = new GTItemHammerIron();
	public static final GTItemAdvancedDrill advancedDrill = new GTItemAdvancedDrill();
	public static final GTItemAdvancedChainsaw advancedChainsaw = new GTItemAdvancedChainsaw();
	public static final GTItemLitiumBattery lithiumBattery = new GTItemLitiumBattery();
	public static final GTItemLapotronicEnergyOrb lapotronicEnergyOrb = new GTItemLapotronicEnergyOrb();
	public static final GTItemLithiumBatpack lithiumBatpack = new GTItemLithiumBatpack();
	public static final GTItemDusts
	dustEnderpearl = new GTItemDusts(GTItemDustTypes.ENDERPEARL),
    dustEnderEye = new GTItemDusts(GTItemDustTypes.ENDER_EYE),
	dustLazurite = new GTItemDusts(GTItemDustTypes.LAZURITE),
	dustPyrite = new GTItemDusts(GTItemDustTypes.PYRITE),
	dustCalcite = new GTItemDusts(GTItemDustTypes.CALCITE),
	dustSodalite = new GTItemDusts(GTItemDustTypes.SODALITE),
	dustNetherrack = new GTItemDusts(GTItemDustTypes.NETHERRACK),
	dustFlintGT = new GTItemDusts(GTItemDustTypes.FLINT),
	dustSulfurGT = new GTItemDusts(GTItemDustTypes.SULFUR),
	dustSaltpeterGT = new GTItemDusts(GTItemDustTypes.SALTPETER),
	dustEndstone = new GTItemDusts(GTItemDustTypes.ENDSTONE),
	dustCinnabar = new GTItemDusts(GTItemDustTypes.CINNABAR),
	dustMaganese = new GTItemDusts(GTItemDustTypes.MAGANESE),
	dustMagnesiumGT = new GTItemDusts(GTItemDustTypes.MAGNESIUM),
	dustSphalerite = new GTItemDusts(GTItemDustTypes.SPHALERITE),
	dustWoodPulp = new GTItemDusts(GTItemDustTypes.WOOD_PULP),
	dustUraniumGT = new GTItemDusts(GTItemDustTypes.URANIUM),
	dustBauxiteGT = new GTItemDusts(GTItemDustTypes.BAUXITE),
	dustAluminum = new GTItemDusts(GTItemDustTypes.ALUMINUM),
	dustTitaniumGT = new GTItemDusts(GTItemDustTypes.TITANIUM),
	dustChrome = new GTItemDusts(GTItemDustTypes.CHROME),
	dustElectrumGT = new GTItemDusts(GTItemDustTypes.ELECTRUM),
	dustTungstenGT = new GTItemDusts(GTItemDustTypes.TUNGSTEN),
	dustLeadGT = new GTItemDusts(GTItemDustTypes.LEAD),
	dustZincGT = new GTItemDusts(GTItemDustTypes.ZINC),
	dustBrassGT = new GTItemDusts(GTItemDustTypes.BRASS),
	dustSteelGT = new GTItemDusts(GTItemDustTypes.STEEL),
	dustPlatinumGT = new GTItemDusts(GTItemDustTypes.PLATINUM),
	dustNickelGT = new GTItemDusts(GTItemDustTypes.NICKEL),
	dustInvarGT = new GTItemDusts(GTItemDustTypes.INVAR),
	dustOsmiumGT = new GTItemDusts(GTItemDustTypes.OSMIUM),
	dustRubyGT = new GTItemDusts(GTItemDustTypes.RUBY),
	dustSapphireGT = new GTItemDusts(GTItemDustTypes.SAPPHIRE),
	dustGreenSapphireGT = new GTItemDusts(GTItemDustTypes.GREEN_SAPPHIRE),
	dustEmerald = new GTItemDusts(GTItemDustTypes.EMERALD),
	dustDiamondGT = new GTItemDusts(GTItemDustTypes.DIAMOND),
	dustOlivine = new GTItemDusts(GTItemDustTypes.OLIVINE),
	dustGalena = new GTItemDusts(GTItemDustTypes.GALENA),
	dustPhosphor = new GTItemDusts(GTItemDustTypes.PHOSPHOR),
	dustRedGarnet = new GTItemDusts(GTItemDustTypes.RED_GARNET),
	dustYellowGarnet = new GTItemDusts(GTItemDustTypes.YELLOW_GARNET),
	dustPyrope = new GTItemDusts(GTItemDustTypes.PYROPE),
	dustAlmandine = new GTItemDusts(GTItemDustTypes.ALMANDINE),
	dustSpessartine = new GTItemDusts(GTItemDustTypes.SPESSARTINE),
	dustAndradite = new GTItemDusts(GTItemDustTypes.ANDRADITE),
	dustGrossular = new GTItemDusts(GTItemDustTypes.GROSSULAR),
	dustUvarovite = new GTItemDusts(GTItemDustTypes.UVAROVITE),
	dustAshes = new GTItemDusts(GTItemDustTypes.ASHES),
	dustDarkAshes = new GTItemDusts(GTItemDustTypes.DARK_ASHES),
	dustRedRock = new GTItemDusts(GTItemDustTypes.REDROCK),
	dustMarble = new GTItemDusts(GTItemDustTypes.MARBLE),
	dustBasalt = new GTItemDusts(GTItemDustTypes.BASALT),
	dustThoriumGT = new GTItemDusts(GTItemDustTypes.THORIUM),
	dustPlutoniumGT = new GTItemDusts(GTItemDustTypes.PLUTONIUM);

	public static final GTItemTinyDusts
	tinyDustEnderpearl = new GTItemTinyDusts(GTItemTinyDustTypes.ENDERPEARL),
    tinyDustEnderEye = new GTItemTinyDusts(GTItemTinyDustTypes.ENDER_EYE),
	tinyDustLazurite = new GTItemTinyDusts(GTItemTinyDustTypes.LAZURITE),
	tinyDustPyrite = new GTItemTinyDusts(GTItemTinyDustTypes.PYRITE),
	tinyDustCalcite = new GTItemTinyDusts(GTItemTinyDustTypes.CALCITE),
	tinyDustSodalite = new GTItemTinyDusts(GTItemTinyDustTypes.SODALITE),
	tinyDustNetherrack = new GTItemTinyDusts(GTItemTinyDustTypes.NETHERRACK),
	tinyDustFlintGT = new GTItemTinyDusts(GTItemTinyDustTypes.FLINT),
	tinyDustSulfurGT = new GTItemTinyDusts(GTItemTinyDustTypes.SULFUR),
	tinyDustSaltpeterGT = new GTItemTinyDusts(GTItemTinyDustTypes.SALTPETER),
	tinyDustEndstone = new GTItemTinyDusts(GTItemTinyDustTypes.ENDSTONE),
	tinyDustCinnabar = new GTItemTinyDusts(GTItemTinyDustTypes.CINNABAR),
	tinyDustMaganese = new GTItemTinyDusts(GTItemTinyDustTypes.MAGANESE),
	tinyDustMagnesiumGT = new GTItemTinyDusts(GTItemTinyDustTypes.MAGNESIUM),
	tinyDustSphalerite = new GTItemTinyDusts(GTItemTinyDustTypes.SPHALERITE),
	tinyDustWoodPulp = new GTItemTinyDusts(GTItemTinyDustTypes.WOOD_PULP),
	tinyDustUraniumGT = new GTItemTinyDusts(GTItemTinyDustTypes.URANIUM),
	tinyDustBauxiteGT = new GTItemTinyDusts(GTItemTinyDustTypes.BAUXITE),
	tinyDustAluminum = new GTItemTinyDusts(GTItemTinyDustTypes.ALUMINUM),
	tinyDustTitaniumGT = new GTItemTinyDusts(GTItemTinyDustTypes.TITANIUM),
	tinyDustChrome = new GTItemTinyDusts(GTItemTinyDustTypes.CHROME),
	tinyDustElectrumGT = new GTItemTinyDusts(GTItemTinyDustTypes.ELECTRUM),
	tinyDustTungstenGT = new GTItemTinyDusts(GTItemTinyDustTypes.TUNGSTEN),
	tinyDustLeadGT = new GTItemTinyDusts(GTItemTinyDustTypes.LEAD),
	tinyDustZincGT = new GTItemTinyDusts(GTItemTinyDustTypes.ZINC),
	tinyDustBrassGT = new GTItemTinyDusts(GTItemTinyDustTypes.BRASS),
	tinyDustSteelGT = new GTItemTinyDusts(GTItemTinyDustTypes.STEEL),
	tinyDustPlatinumGT = new GTItemTinyDusts(GTItemTinyDustTypes.PLATINUM),
	tinyDustNickelGT = new GTItemTinyDusts(GTItemTinyDustTypes.NICKEL),
	tinyDustInvarGT = new GTItemTinyDusts(GTItemTinyDustTypes.INVAR),
	tinyDustOsmiumGT = new GTItemTinyDusts(GTItemTinyDustTypes.OSMIUM),
	tinyDustRubyGT = new GTItemTinyDusts(GTItemTinyDustTypes.RUBY),
	tinyDustSapphireGT = new GTItemTinyDusts(GTItemTinyDustTypes.SAPPHIRE),
	tinyDustGreenSapphireGT = new GTItemTinyDusts(GTItemTinyDustTypes.GREEN_SAPPHIRE),
	tinyDustEmerald = new GTItemTinyDusts(GTItemTinyDustTypes.EMERALD),
	tinyDustDiamondGT = new GTItemTinyDusts(GTItemTinyDustTypes.DIAMOND),
	tinyDustOlivine = new GTItemTinyDusts(GTItemTinyDustTypes.OLIVINE),
	tinyDustGalena = new GTItemTinyDusts(GTItemTinyDustTypes.GALENA),
	tinyDustPhosphor = new GTItemTinyDusts(GTItemTinyDustTypes.PHOSPHOR),
	tinyDustObsidian = new GTItemTinyDusts(GTItemTinyDustTypes.OBSIDIAN),
	tinyDustCharcoal = new GTItemTinyDusts(GTItemTinyDustTypes.CHARCOAL),
	tinyDustRedGarnet = new GTItemTinyDusts(GTItemTinyDustTypes.RED_GARNET),
	tinyDustYellowGarnet = new GTItemTinyDusts(GTItemTinyDustTypes.YELLOW_GARNET),
	tinyDustPyrope = new GTItemTinyDusts(GTItemTinyDustTypes.PYROPE),
	tinyDustAlmandine = new GTItemTinyDusts(GTItemTinyDustTypes.ALMANDINE),
	tinyDustSpessartine = new GTItemTinyDusts(GTItemTinyDustTypes.SPESSARTINE),
	tinyDustAndradite = new GTItemTinyDusts(GTItemTinyDustTypes.ANDRADITE),
	tinyDustGrossular = new GTItemTinyDusts(GTItemTinyDustTypes.GROSSULAR),
	tinyDustUvarovite = new GTItemTinyDusts(GTItemTinyDustTypes.UVAROVITE),
	tinyDustAshes = new GTItemTinyDusts(GTItemTinyDustTypes.ASHES),
	tinyDustDarkAshes = new GTItemTinyDusts(GTItemTinyDustTypes.DARK_ASHES),
	tinyDustRedRock = new GTItemTinyDusts(GTItemTinyDustTypes.REDROCK),
	tinyDustMarble = new GTItemTinyDusts(GTItemTinyDustTypes.MARBLE),
	tinyDustBasalt = new GTItemTinyDusts(GTItemTinyDustTypes.BASALT),
	tinyDustThoriumGT = new GTItemTinyDusts(GTItemTinyDustTypes.THORIUM),
	tinyDustPlutoniumGT = new GTItemTinyDusts(GTItemTinyDustTypes.PLUTONIUM),
	tinyDustCoal = new GTItemTinyDusts(GTItemTinyDustTypes.COAL),
	tinyDustIron = new GTItemTinyDusts(GTItemTinyDustTypes.IRON),
	tinyDustGold = new GTItemTinyDusts(GTItemTinyDustTypes.GOLD),
	tinyDustCopper = new GTItemTinyDusts(GTItemTinyDustTypes.COPPER),
	tinyDustTin = new GTItemTinyDusts(GTItemTinyDustTypes.TIN),
	tinyDustBronze = new GTItemTinyDusts(GTItemTinyDustTypes.BRONZE),
	tinyDustSilver = new GTItemTinyDusts(GTItemTinyDustTypes.SILVER),
	tinyDustClay = new GTItemTinyDusts(GTItemTinyDustTypes.CLAY),
	tinyDustGunpowder = new GTItemTinyDusts(GTItemTinyDustTypes.GUNPOWDER),
	tinyDustRedstone = new GTItemTinyDusts(GTItemTinyDustTypes.REDSTONE),
	tinyDustGlowstone = new GTItemTinyDusts(GTItemTinyDustTypes.GLOWSTONE);

	public static final GTItemMaterials
	ingotIridiumAlloy = new GTItemMaterials(GTItemMaterialTypes.IRIDIUM_ALLOY_INGOT),
	ingotHotTungstensteel = new GTItemMaterials(GTItemMaterialTypes.HOT_TUNGSTENSTEEL_INGOT),
	ingotTungstensteel = new GTItemMaterials(GTItemMaterialTypes.TUNGSTENSTEEL_INGOT),
	ingotIridiumGT = new GTItemMaterials(GTItemMaterialTypes.IRIDIUM_INGOT),
	ingotAluminum = new GTItemMaterials(GTItemMaterialTypes.ALUMINUM_INGOT),
	ingotTitaniumGT = new GTItemMaterials(GTItemMaterialTypes.TITANIUM_INGOT),
	ingotChromeGT = new GTItemMaterials(GTItemMaterialTypes.CHROME_INGOT),
	ingotElectrumGT = new GTItemMaterials(GTItemMaterialTypes.ELECTRUM_INGOT),
	ingotTungstenGT = new GTItemMaterials(GTItemMaterialTypes.TUNGSTEN_INGOT),
	ingotLeadGT = new GTItemMaterials(GTItemMaterialTypes.LEAD_INGOT),
	ingotZincGT = new GTItemMaterials(GTItemMaterialTypes.ZINC_INGOT),
	ingotBrassGT = new GTItemMaterials(GTItemMaterialTypes.BRASS_INGOT),
	ingotSteelGT = new GTItemMaterials(GTItemMaterialTypes.STEEL_INGOT),
	ingotPlatinumGT = new GTItemMaterials(GTItemMaterialTypes.PLATINUM_INGOT),
	ingotNickelGT = new GTItemMaterials(GTItemMaterialTypes.NICKEL_INGOT),
	ingotInvarGT = new GTItemMaterials(GTItemMaterialTypes.INVAR_INGOT),
	ingotOsmiumGT = new GTItemMaterials(GTItemMaterialTypes.OSMIUM_INGOT),
	rubyGT = new GTItemMaterials(GTItemMaterialTypes.RUBY),
	sapphireGT = new GTItemMaterials(GTItemMaterialTypes.SAPPHIRE),
	greenSapphire = new GTItemMaterials(GTItemMaterialTypes.GREEN_SAPPHIRE),
	lazuriteChunk = new GTItemMaterials(GTItemMaterialTypes.LAZURITE_CHUNK),
	plateSiliconGT = new GTItemMaterials(GTItemMaterialTypes.SILICON_PLATE),
	olivine = new GTItemMaterials(GTItemMaterialTypes.OLIVINE),
	ingotThoriumGT = new GTItemMaterials(GTItemMaterialTypes.THORIUM_INGOT),
	ingotPlutoniumGT = new GTItemMaterials(GTItemMaterialTypes.PLUTONIUM_INGOT),
	redGarnet = new GTItemMaterials(GTItemMaterialTypes.RED_GARNET),
	yellowGarnet = new GTItemMaterials(GTItemMaterialTypes.YELLOW_GARNET),
	plateIronGT = new GTItemMaterials(GTItemMaterialTypes.IRON_PLATE),
	plateGold = new GTItemMaterials(GTItemMaterialTypes.GOLD_PLATE),
	plateRefinedIronGT = new GTItemMaterials(GTItemMaterialTypes.REFINED_IRON_PLATE),
	plateTin = new GTItemMaterials(GTItemMaterialTypes.TIN_PLATE),
	plateCopperGT = new GTItemMaterials(GTItemMaterialTypes.COPPER_PLATE),
	plateSilver = new GTItemMaterials(GTItemMaterialTypes.SILVER_PLATE),
	plateBronzeGT = new GTItemMaterials(GTItemMaterialTypes.BRONZE_PLATE),
	plateElectrumGT = new GTItemMaterials(GTItemMaterialTypes.ELECTRUM_PLATE),
	plateNickel = new GTItemMaterials(GTItemMaterialTypes.NICKEL_PLATE),
	plateInvar = new GTItemMaterials(GTItemMaterialTypes.INVAR_PLATE),
	plateLead = new GTItemMaterials(GTItemMaterialTypes.LEAD_PLATE),
	plateAluminum = new GTItemMaterials(GTItemMaterialTypes.ALUMINUM_PLATE),
	plateChrome = new GTItemMaterials(GTItemMaterialTypes.CHROME_PLATE),
	plateTitaniumGT = new GTItemMaterials(GTItemMaterialTypes.TITANIUM_PLATE),
	plateSteelGT = new GTItemMaterials(GTItemMaterialTypes.STEEL_PLATE),
	platePlatinumGT = new GTItemMaterials(GTItemMaterialTypes.PLATINUM_PLATE),
	plateTungstenGT = new GTItemMaterials(GTItemMaterialTypes.TUNGSTEN_PLATE),
	plateBrassGT = new GTItemMaterials(GTItemMaterialTypes.BRASS_PLATE),
	plateZinc = new GTItemMaterials(GTItemMaterialTypes.ZINC_PLATE),
	plateTungstensteel = new GTItemMaterials(GTItemMaterialTypes.TUNGSTENSTEEL_PLATE),
	plateOsmium = new GTItemMaterials(GTItemMaterialTypes.OSMIUM_PLATE),
	plateMagnaliumGT = new GTItemMaterials(GTItemMaterialTypes.MAGNALIUM_PLATE),
	flour = new GTItemMaterials(GTItemMaterialTypes.FLOUR),
	plateWood = new GTItemMaterials(GTItemMaterialTypes.WOOD_PLATE);
	
	public static final GTItemNuggets
	nuggetIridium = new GTItemNuggets(GTItemNuggetTypes.IRIDIUM),
	nuggetSilver = new GTItemNuggets(GTItemNuggetTypes.SILVER),
	nuggetAluminum = new GTItemNuggets(GTItemNuggetTypes.ALUMINUM),
	nuggetTitanium = new GTItemNuggets(GTItemNuggetTypes.TITANIUM),
	nuggetChrome = new GTItemNuggets(GTItemNuggetTypes.CHROME),
	nuggetElectrum = new GTItemNuggets(GTItemNuggetTypes.ELECTRUM),
	nuggetTungsten = new GTItemNuggets(GTItemNuggetTypes.TUNGSTEN),
	nuggetLead = new GTItemNuggets(GTItemNuggetTypes.LEAD),
	nuggetZinc = new GTItemNuggets(GTItemNuggetTypes.ZINC),
	nuggetBrass = new GTItemNuggets(GTItemNuggetTypes.BRASS),
	nuggetSteel = new GTItemNuggets(GTItemNuggetTypes.STEEL),
	nuggetPlatinum = new GTItemNuggets(GTItemNuggetTypes.PLATINUM),
	nuggetNickel = new GTItemNuggets(GTItemNuggetTypes.NICKEL),
	nuggetInvar = new GTItemNuggets(GTItemNuggetTypes.INVAR),
	nuggetOsmium = new GTItemNuggets(GTItemNuggetTypes.OSMIUM),
	nuggetCopperGT = new GTItemNuggets(GTItemNuggetTypes.COPPER),
	nuggetTin = new GTItemNuggets(GTItemNuggetTypes.TIN),
	nuggetBronze = new GTItemNuggets(GTItemNuggetTypes.BRONZE);

	public static final GTItemComponents
	energyFlowCircuit = new GTItemComponents(GTItemComponentTypes.ENERGY_FLOW_CIRCUIT),
	dataControlCircuit = new GTItemComponents(GTItemComponentTypes.DATA_CONTROL_CIRCUIT),
	superConductor = new GTItemComponents(GTItemComponentTypes.SUPERCONDUCTOR),
	dataStorageCircuit = new GTItemComponents(GTItemComponentTypes.DATA_STORAGE_CIRCUIT),
	computerMonitor = new GTItemComponents(GTItemComponentTypes.COMPUTER_MONITOR),
	conveyorModule = new GTItemComponents(GTItemComponentTypes.CONVEYOR_MODULE),
	braintechAerospaceARDT = new GTItemComponents(GTItemComponentTypes.BRAINTECH_AEROSPACE_ARDT),
	diamondSawblade = new GTItemComponents(GTItemComponentTypes.DIAMOND_SAWBLADE),
	diamondGrinder = new GTItemComponents(GTItemComponentTypes.DIAMOND_GRINDER),
	kanthalHeatingCoil = new GTItemComponents(GTItemComponentTypes.KANTHAL_HEATING_COIL),
	nichromeHeatingCoil = new GTItemComponents(GTItemComponentTypes.NICHROME_HEATING_COIL),
	cupronickelHeatingCoil = new GTItemComponents(GTItemComponentTypes.CUPRONICKEL_HEATING_COIL),
	machineParts = new GTItemComponents(GTItemComponentTypes.MACHINE_PARTS),
	wolframiumGrinder = new GTItemComponents(GTItemComponentTypes.WOLFRAMIUM_GRINDER),
	advancedCircuitParts = new GTItemComponents(GTItemComponentTypes.ADVANCED_CIRCUIT_PARTS),
	aluminumMachineHull = new GTItemComponents(GTItemComponentTypes.ALUMINUM_MACHINE_HULL),
	bronzeMachineHull = new GTItemComponents(GTItemComponentTypes.BRONZE_MACHINE_HULL),
	brassMachineHull = new GTItemComponents(GTItemComponentTypes.BRASS_MACHINE_HULL),
	steelMachineHull = new GTItemComponents(GTItemComponentTypes.STEEL_MACHINE_HULL),
	titaniumMachineHull = new GTItemComponents(GTItemComponentTypes.TITANIUM_MACHINE_HULL),
	basicCircuitBoard = new GTItemComponents(GTItemComponentTypes.BASIC_CIRCUIT_BOARD),
	advancedCircuitBoard = new GTItemComponents(GTItemComponentTypes.ADVANCED_CIRCUIT_BOARD),
	eliteCircuitBoard = new GTItemComponents(GTItemComponentTypes.ELITE_CIRCUIT_BOARD);

	@Mod.EventBusSubscriber(modid = GTClassic.MODID)
	public static class RegistrationHandler {
		public static final Item[] items = {
				creditDoge,
				creditAlk,
				hammerIron,
				advancedDrill,
				advancedChainsaw,
				lithiumBattery,
				lapotronicEnergyOrb,
				lithiumBatpack,
				
				dustEnderpearl,
			    dustEnderEye,
				dustLazurite,
				dustPyrite,
				dustCalcite,
				dustSodalite,
				dustNetherrack,
				dustFlintGT,
				dustSulfurGT,
				dustSaltpeterGT,
				dustEndstone,
				dustCinnabar,
				dustMaganese,
				dustMagnesiumGT,
				dustSphalerite,
				dustWoodPulp,
				dustUraniumGT,
				dustBauxiteGT,
				dustAluminum,
				dustTitaniumGT,
				dustChrome,
				dustElectrumGT,
				dustTungstenGT,
				dustLeadGT,
				dustZincGT,
				dustBrassGT,
				dustSteelGT,
				dustPlatinumGT,
				dustNickelGT,
				dustInvarGT,
				dustOsmiumGT,
				dustRubyGT,
				dustSapphireGT,
				dustGreenSapphireGT,
				dustEmerald,
				dustDiamondGT,
				dustOlivine,
				dustGalena,
				dustPhosphor,
				dustRedGarnet,
				dustYellowGarnet,
				dustPyrope,
				dustAlmandine,
				dustSpessartine,
				dustAndradite,
				dustGrossular,
				dustUvarovite,
				dustAshes,
				dustDarkAshes,
				dustRedRock,
				dustMarble,
				dustBasalt,
				dustThoriumGT,
				dustPlutoniumGT,
				
				tinyDustEnderpearl,
			    tinyDustEnderEye,
				tinyDustLazurite,
				tinyDustPyrite,
				tinyDustCalcite,
				tinyDustSodalite,
				tinyDustNetherrack,
				tinyDustFlintGT,
				tinyDustSulfurGT,
				tinyDustSaltpeterGT,
				tinyDustEndstone,
				tinyDustCinnabar,
				tinyDustMaganese,
				tinyDustMagnesiumGT,
				tinyDustSphalerite,
				tinyDustWoodPulp,
				tinyDustUraniumGT,
				tinyDustBauxiteGT,
				tinyDustAluminum,
				tinyDustTitaniumGT,
				tinyDustChrome,
				tinyDustElectrumGT,
				tinyDustTungstenGT,
				tinyDustLeadGT,
				tinyDustZincGT,
				tinyDustBrassGT,
				tinyDustSteelGT,
				tinyDustPlatinumGT,
				tinyDustNickelGT,
				tinyDustInvarGT,
				tinyDustOsmiumGT,
				tinyDustRubyGT,
				tinyDustSapphireGT,
				tinyDustGreenSapphireGT,
				tinyDustEmerald,
				tinyDustDiamondGT,
				tinyDustOlivine,
				tinyDustGalena,
				tinyDustPhosphor,
				tinyDustObsidian,
				tinyDustCharcoal,
				tinyDustRedGarnet,
				tinyDustYellowGarnet,
				tinyDustPyrope,
				tinyDustAlmandine,
				tinyDustSpessartine,
				tinyDustAndradite,
				tinyDustGrossular,
				tinyDustUvarovite,
				tinyDustAshes,
				tinyDustDarkAshes,
				tinyDustRedRock,
				tinyDustMarble,
				tinyDustBasalt,
				tinyDustThoriumGT,
				tinyDustPlutoniumGT,
				tinyDustCoal,
				tinyDustIron,
				tinyDustGold,
				tinyDustCopper,
				tinyDustTin,
				tinyDustBronze,
				tinyDustSilver,
				tinyDustClay,
				tinyDustGunpowder,
				tinyDustRedstone,
				tinyDustGlowstone,
				
				ingotIridiumAlloy,
				ingotHotTungstensteel,
				ingotTungstensteel,
				ingotIridiumGT,
				ingotAluminum,
				ingotTitaniumGT,
				ingotChromeGT,
				ingotElectrumGT,
				ingotTungstenGT,
				ingotLeadGT,
				ingotZincGT,
				ingotBrassGT,
				ingotSteelGT,
				ingotPlatinumGT,
				ingotNickelGT,
				ingotInvarGT,
				ingotOsmiumGT,
				rubyGT,
				sapphireGT,
				greenSapphire,
				lazuriteChunk,
				plateSiliconGT,
				olivine,
				ingotThoriumGT,
				ingotPlutoniumGT,
				redGarnet,
				yellowGarnet,
				plateIronGT,
				plateGold,
				plateRefinedIronGT,
				plateTin,
				plateCopperGT,
				plateSilver,
				plateBronzeGT,
				plateElectrumGT,
				plateNickel,
				plateInvar,
				plateLead,
				plateAluminum,
				plateChrome,
				plateTitaniumGT,
				plateSteelGT,
				platePlatinumGT,
				plateTungstenGT,
				plateBrassGT,
				plateZinc,
				plateTungstensteel,
				plateOsmium,
				plateMagnaliumGT,
				flour,
				plateWood,
				
				nuggetIridium,
				nuggetSilver,
				nuggetAluminum,
				nuggetTitanium,
				nuggetChrome,
				nuggetElectrum,
				nuggetTungsten,
				nuggetLead,
				nuggetZinc,
				nuggetBrass,
				nuggetSteel,
				nuggetPlatinum,
				nuggetNickel,
				nuggetInvar,
				nuggetOsmium,
				nuggetCopperGT,
				nuggetTin,
				nuggetBronze,
				
				energyFlowCircuit,
				dataControlCircuit,
				superConductor,
				dataStorageCircuit,
				computerMonitor,
				conveyorModule,
				braintechAerospaceARDT,
				diamondSawblade,
				diamondGrinder,
				kanthalHeatingCoil,
				nichromeHeatingCoil,
				cupronickelHeatingCoil,
				machineParts,
				wolframiumGrinder,
				advancedCircuitParts,
				aluminumMachineHull,
				bronzeMachineHull,
				brassMachineHull,
				steelMachineHull,
				titaniumMachineHull,
				basicCircuitBoard,
				advancedCircuitBoard,
				eliteCircuitBoard
				
		};
		@SubscribeEvent
		public static void registerItems(RegistryEvent.Register<Item> event) {
			IForgeRegistry registry = event.getRegistry();
			//items
			GTClassic.logger.info("Registering Items");
			for (Item item : items)
			{
				registry.register(item);
			}
		}
	}
	//inits textures for items
	@SideOnly(Side.CLIENT)
    public static void initModels() {
        creditDoge.initModel();
        creditAlk.initModel();
        hammerIron.initModel();
    }
}
