package gtclassic.util;

import gtclassic.GTClassic;
import gtclassic.items.*;
import gtclassic.items.GTItemDusts.GTItemDustTypes;
import gtclassic.items.GTItemTinyDusts.GTItemTinyDustTypes;
import gtclassic.items.GTItemNuggets.GTItemNuggetTypes;
import gtclassic.items.GTItemMaterials.GTItemMaterialTypes;
import gtclassic.items.GTItemComponents.GTItemComponentTypes;
import gtclassic.items.armor.GTItemEnergyPack;
import gtclassic.items.eustorage.GTItemLapotronicEnergyOrb;
import gtclassic.items.eustorage.GTItemLitiumBattery;
import gtclassic.items.tools.GTItemAdvancedChainsaw;
import gtclassic.items.tools.GTItemAdvancedDrill;
import gtclassic.items.tools.GTItemHammerIron;
import gtclassic.items.tools.GTItemMortar;
import net.minecraft.item.Item;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;
import net.minecraftforge.registries.IForgeRegistry;

public class GTItems {

    public static final GTItemCreditDoge creditDoge = new GTItemCreditDoge();
	public static final GTItemCreditAlk creditAlk = new GTItemCreditAlk();
	public static final GTItemMortar mortarIron = new GTItemMortar(95, "iron_mortar", "mortarIron", 30);
	public static final GTItemMortar mortarFlint = new GTItemMortar(7, "flint_mortar", "mortarFlint", 31);
	public static final GTItemHammerIron hammerIron = new GTItemHammerIron();
	public static final GTItemAdvancedDrill advancedDrill = new GTItemAdvancedDrill();
	public static final GTItemAdvancedChainsaw advancedChainsaw = new GTItemAdvancedChainsaw();
	public static final GTItemLitiumBattery lithiumBattery = new GTItemLitiumBattery();
	public static final GTItemLapotronicEnergyOrb lapotronicEnergyOrb = new GTItemLapotronicEnergyOrb();
	public static final GTItemEnergyPack lithiumBatpack = new GTItemEnergyPack(58, "gtclassic:textures/models/armor/lithiumbatpack", 600000, "lithium_batpack", ".lithiumBatpack", 1, 200);
	public static final GTItemEnergyPack lapotronPack = new GTItemEnergyPack(45, "gtclassic:textures/models/armor/lapotronpack", 100000000, "lapotron_pack", ".lapotronPack", 3, 1500);
	public static final GTItemDusts
	dustEnderpearl = new GTItemDusts(GTItemDustTypes.ENDERPEARL),
    dustEnderEye = new GTItemDusts(GTItemDustTypes.ENDER_EYE),
	dustLazurite = new GTItemDusts(GTItemDustTypes.LAZURITE),
	dustPyrite = new GTItemDusts(GTItemDustTypes.PYRITE),
	dustCalcite = new GTItemDusts(GTItemDustTypes.CALCITE),
	dustSodalite = new GTItemDusts(GTItemDustTypes.SODALITE),
	dustNetherrack = new GTItemDusts(GTItemDustTypes.NETHERRACK),
	dustFlint = new GTItemDusts(GTItemDustTypes.FLINT),
	dustSulfur = new GTItemDusts(GTItemDustTypes.SULFUR),
	dustSaltpeter = new GTItemDusts(GTItemDustTypes.SALTPETER),
	dustEndstone = new GTItemDusts(GTItemDustTypes.ENDSTONE),
	dustCinnabar = new GTItemDusts(GTItemDustTypes.CINNABAR),
	dustMaganese = new GTItemDusts(GTItemDustTypes.MAGANESE),
	dustMagnesium = new GTItemDusts(GTItemDustTypes.MAGNESIUM),
	dustSphalerite = new GTItemDusts(GTItemDustTypes.SPHALERITE),
	dustWoodPulp = new GTItemDusts(GTItemDustTypes.WOOD_PULP),
	dustUranium = new GTItemDusts(GTItemDustTypes.URANIUM),
	dustBauxite = new GTItemDusts(GTItemDustTypes.BAUXITE),
	dustAluminum = new GTItemDusts(GTItemDustTypes.ALUMINUM),
	dustTitanium = new GTItemDusts(GTItemDustTypes.TITANIUM),
	dustChrome = new GTItemDusts(GTItemDustTypes.CHROME),
	dustElectrum = new GTItemDusts(GTItemDustTypes.ELECTRUM),
	dustTungsten = new GTItemDusts(GTItemDustTypes.TUNGSTEN),
	dustLead = new GTItemDusts(GTItemDustTypes.LEAD),
	dustZinc = new GTItemDusts(GTItemDustTypes.ZINC),
	dustBrass = new GTItemDusts(GTItemDustTypes.BRASS),
	dustSteel = new GTItemDusts(GTItemDustTypes.STEEL),
	dustPlatinum = new GTItemDusts(GTItemDustTypes.PLATINUM),
	dustNickel = new GTItemDusts(GTItemDustTypes.NICKEL),
	dustInvar = new GTItemDusts(GTItemDustTypes.INVAR),
	dustOsmium = new GTItemDusts(GTItemDustTypes.OSMIUM),
	dustRuby = new GTItemDusts(GTItemDustTypes.RUBY),
	dustSapphire = new GTItemDusts(GTItemDustTypes.SAPPHIRE),
	dustGreenSapphire = new GTItemDusts(GTItemDustTypes.GREEN_SAPPHIRE),
	dustEmerald = new GTItemDusts(GTItemDustTypes.EMERALD),
	dustDiamond = new GTItemDusts(GTItemDustTypes.DIAMOND),
	dustOlivine = new GTItemDusts(GTItemDustTypes.OLIVINE),
	dustGalena = new GTItemDusts(GTItemDustTypes.GALENA),
	dustPhosphor = new GTItemDusts(GTItemDustTypes.PHOSPHOR),
	dustRedGarnet = new GTItemDusts(GTItemDustTypes.RED_GARNET),
	dustYellowGarnet = new GTItemDusts(GTItemDustTypes.YELLOW_GARNET),
	dustPyrope = new GTItemDusts(GTItemDustTypes.PYROPE),
	dustAlmandine = new GTItemDusts(GTItemDustTypes.ALMANDINE),
	dustSpessartine = new GTItemDusts(GTItemDustTypes.SPESSARTINE),
	dustAndradite = new GTItemDusts(GTItemDustTypes.ANDRADITE),
	dustGrossular = new GTItemDusts(GTItemDustTypes.GROSSULAR),
	dustUvarovite = new GTItemDusts(GTItemDustTypes.UVAROVITE),
	dustAshes = new GTItemDusts(GTItemDustTypes.ASHES),
	dustDarkAshes = new GTItemDusts(GTItemDustTypes.DARK_ASHES),
	dustRedRock = new GTItemDusts(GTItemDustTypes.REDROCK),
	dustMarble = new GTItemDusts(GTItemDustTypes.MARBLE),
	dustBasalt = new GTItemDusts(GTItemDustTypes.BASALT),
	dustThorium = new GTItemDusts(GTItemDustTypes.THORIUM),
	dustPlutonium = new GTItemDusts(GTItemDustTypes.PLUTONIUM);

	public static final GTItemTinyDusts
	tinyDustEnderpearl = new GTItemTinyDusts(GTItemTinyDustTypes.ENDERPEARL),
    tinyDustEnderEye = new GTItemTinyDusts(GTItemTinyDustTypes.ENDER_EYE),
	tinyDustLazurite = new GTItemTinyDusts(GTItemTinyDustTypes.LAZURITE),
	tinyDustPyrite = new GTItemTinyDusts(GTItemTinyDustTypes.PYRITE),
	tinyDustCalcite = new GTItemTinyDusts(GTItemTinyDustTypes.CALCITE),
	tinyDustSodalite = new GTItemTinyDusts(GTItemTinyDustTypes.SODALITE),
	tinyDustNetherrack = new GTItemTinyDusts(GTItemTinyDustTypes.NETHERRACK),
	tinyDustFlint = new GTItemTinyDusts(GTItemTinyDustTypes.FLINT),
	tinyDustSulfur = new GTItemTinyDusts(GTItemTinyDustTypes.SULFUR),
	tinyDustSaltpeter = new GTItemTinyDusts(GTItemTinyDustTypes.SALTPETER),
	tinyDustEndstone = new GTItemTinyDusts(GTItemTinyDustTypes.ENDSTONE),
	tinyDustCinnabar = new GTItemTinyDusts(GTItemTinyDustTypes.CINNABAR),
	tinyDustMaganese = new GTItemTinyDusts(GTItemTinyDustTypes.MAGANESE),
	tinyDustMagnesium = new GTItemTinyDusts(GTItemTinyDustTypes.MAGNESIUM),
	tinyDustSphalerite = new GTItemTinyDusts(GTItemTinyDustTypes.SPHALERITE),
	tinyDustWoodPulp = new GTItemTinyDusts(GTItemTinyDustTypes.WOOD_PULP),
	tinyDustUranium = new GTItemTinyDusts(GTItemTinyDustTypes.URANIUM),
	tinyDustBauxite = new GTItemTinyDusts(GTItemTinyDustTypes.BAUXITE),
	tinyDustAluminum = new GTItemTinyDusts(GTItemTinyDustTypes.ALUMINUM),
	tinyDustTitanium = new GTItemTinyDusts(GTItemTinyDustTypes.TITANIUM),
	tinyDustChrome = new GTItemTinyDusts(GTItemTinyDustTypes.CHROME),
	tinyDustElectrum = new GTItemTinyDusts(GTItemTinyDustTypes.ELECTRUM),
	tinyDustTungsten = new GTItemTinyDusts(GTItemTinyDustTypes.TUNGSTEN),
	tinyDustLead = new GTItemTinyDusts(GTItemTinyDustTypes.LEAD),
	tinyDustZinc = new GTItemTinyDusts(GTItemTinyDustTypes.ZINC),
	tinyDustBrass = new GTItemTinyDusts(GTItemTinyDustTypes.BRASS),
	tinyDustSteel = new GTItemTinyDusts(GTItemTinyDustTypes.STEEL),
	tinyDustPlatinum = new GTItemTinyDusts(GTItemTinyDustTypes.PLATINUM),
	tinyDustNickel = new GTItemTinyDusts(GTItemTinyDustTypes.NICKEL),
	tinyDustInvar = new GTItemTinyDusts(GTItemTinyDustTypes.INVAR),
	tinyDustOsmium = new GTItemTinyDusts(GTItemTinyDustTypes.OSMIUM),
	tinyDustRuby = new GTItemTinyDusts(GTItemTinyDustTypes.RUBY),
	tinyDustSapphire = new GTItemTinyDusts(GTItemTinyDustTypes.SAPPHIRE),
	tinyDustGreenSapphire = new GTItemTinyDusts(GTItemTinyDustTypes.GREEN_SAPPHIRE),
	tinyDustEmerald = new GTItemTinyDusts(GTItemTinyDustTypes.EMERALD),
	tinyDustDiamond = new GTItemTinyDusts(GTItemTinyDustTypes.DIAMOND),
	tinyDustOlivine = new GTItemTinyDusts(GTItemTinyDustTypes.OLIVINE),
	tinyDustGalena = new GTItemTinyDusts(GTItemTinyDustTypes.GALENA),
	tinyDustPhosphor = new GTItemTinyDusts(GTItemTinyDustTypes.PHOSPHOR),
	tinyDustObsidian = new GTItemTinyDusts(GTItemTinyDustTypes.OBSIDIAN),
	tinyDustCharcoal = new GTItemTinyDusts(GTItemTinyDustTypes.CHARCOAL),
	tinyDustRedGarnet = new GTItemTinyDusts(GTItemTinyDustTypes.RED_GARNET),
	tinyDustYellowGarnet = new GTItemTinyDusts(GTItemTinyDustTypes.YELLOW_GARNET),
	tinyDustPyrope = new GTItemTinyDusts(GTItemTinyDustTypes.PYROPE),
	tinyDustAlmandine = new GTItemTinyDusts(GTItemTinyDustTypes.ALMANDINE),
	tinyDustSpessartine = new GTItemTinyDusts(GTItemTinyDustTypes.SPESSARTINE),
	tinyDustAndradite = new GTItemTinyDusts(GTItemTinyDustTypes.ANDRADITE),
	tinyDustGrossular = new GTItemTinyDusts(GTItemTinyDustTypes.GROSSULAR),
	tinyDustUvarovite = new GTItemTinyDusts(GTItemTinyDustTypes.UVAROVITE),
	tinyDustAshes = new GTItemTinyDusts(GTItemTinyDustTypes.ASHES),
	tinyDustDarkAshes = new GTItemTinyDusts(GTItemTinyDustTypes.DARK_ASHES),
	tinyDustRedRock = new GTItemTinyDusts(GTItemTinyDustTypes.REDROCK),
	tinyDustMarble = new GTItemTinyDusts(GTItemTinyDustTypes.MARBLE),
	tinyDustBasalt = new GTItemTinyDusts(GTItemTinyDustTypes.BASALT),
	tinyDustThorium = new GTItemTinyDusts(GTItemTinyDustTypes.THORIUM),
	tinyDustPlutonium = new GTItemTinyDusts(GTItemTinyDustTypes.PLUTONIUM),
	tinyDustCoal = new GTItemTinyDusts(GTItemTinyDustTypes.COAL),
	tinyDustIron = new GTItemTinyDusts(GTItemTinyDustTypes.IRON),
	tinyDustGold = new GTItemTinyDusts(GTItemTinyDustTypes.GOLD),
	tinyDustCopper = new GTItemTinyDusts(GTItemTinyDustTypes.COPPER),
	tinyDustTin = new GTItemTinyDusts(GTItemTinyDustTypes.TIN),
	tinyDustBronze = new GTItemTinyDusts(GTItemTinyDustTypes.BRONZE),
	tinyDustSilver = new GTItemTinyDusts(GTItemTinyDustTypes.SILVER),
	tinyDustClay = new GTItemTinyDusts(GTItemTinyDustTypes.CLAY),
	tinyDustGunpowder = new GTItemTinyDusts(GTItemTinyDustTypes.GUNPOWDER),
	tinyDustRedstone = new GTItemTinyDusts(GTItemTinyDustTypes.REDSTONE),
	tinyDustGlowstone = new GTItemTinyDusts(GTItemTinyDustTypes.GLOWSTONE);

	public static final GTItemMaterials
	ingotIridiumAlloy = new GTItemMaterials(GTItemMaterialTypes.IRIDIUM_ALLOY_INGOT),
	ingotHotTungstensteel = new GTItemMaterials(GTItemMaterialTypes.HOT_TUNGSTENSTEEL_INGOT),
	ingotTungstensteel = new GTItemMaterials(GTItemMaterialTypes.TUNGSTENSTEEL_INGOT),
	ingotIridium = new GTItemMaterials(GTItemMaterialTypes.IRIDIUM_INGOT),
	ingotAluminum = new GTItemMaterials(GTItemMaterialTypes.ALUMINUM_INGOT),
	ingotTitanium = new GTItemMaterials(GTItemMaterialTypes.TITANIUM_INGOT),
	ingotTungsten = new GTItemMaterials(GTItemMaterialTypes.TUNGSTEN_INGOT),
	ingotChrome = new GTItemMaterials(GTItemMaterialTypes.CHROME_INGOT),
	ingotElectrum = new GTItemMaterials(GTItemMaterialTypes.ELECTRUM_INGOT),
	ingotLead = new GTItemMaterials(GTItemMaterialTypes.LEAD_INGOT),
	ingotZinc = new GTItemMaterials(GTItemMaterialTypes.ZINC_INGOT),
	ingotBrass = new GTItemMaterials(GTItemMaterialTypes.BRASS_INGOT),
	ingotSteel = new GTItemMaterials(GTItemMaterialTypes.STEEL_INGOT),
	ingotPlatinum = new GTItemMaterials(GTItemMaterialTypes.PLATINUM_INGOT),
	ingotNickel = new GTItemMaterials(GTItemMaterialTypes.NICKEL_INGOT),
	ingotInvar = new GTItemMaterials(GTItemMaterialTypes.INVAR_INGOT),
	ingotOsmium = new GTItemMaterials(GTItemMaterialTypes.OSMIUM_INGOT),
	ruby = new GTItemMaterials(GTItemMaterialTypes.RUBY),
	sapphire = new GTItemMaterials(GTItemMaterialTypes.SAPPHIRE),
	greenSapphire = new GTItemMaterials(GTItemMaterialTypes.GREEN_SAPPHIRE),
	lazuriteChunk = new GTItemMaterials(GTItemMaterialTypes.LAZURITE_CHUNK),
	plateSilicon = new GTItemMaterials(GTItemMaterialTypes.SILICON_PLATE),
	olivine = new GTItemMaterials(GTItemMaterialTypes.OLIVINE),
	ingotThorium = new GTItemMaterials(GTItemMaterialTypes.THORIUM_INGOT),
	ingotPlutonium = new GTItemMaterials(GTItemMaterialTypes.PLUTONIUM_INGOT),
	redGarnet = new GTItemMaterials(GTItemMaterialTypes.RED_GARNET),
	yellowGarnet = new GTItemMaterials(GTItemMaterialTypes.YELLOW_GARNET),
	plateIron = new GTItemMaterials(GTItemMaterialTypes.IRON_PLATE),
	plateGold = new GTItemMaterials(GTItemMaterialTypes.GOLD_PLATE),
	plateRefinedIron = new GTItemMaterials(GTItemMaterialTypes.REFINED_IRON_PLATE),
	plateTin = new GTItemMaterials(GTItemMaterialTypes.TIN_PLATE),
	plateCopper = new GTItemMaterials(GTItemMaterialTypes.COPPER_PLATE),
	plateSilver = new GTItemMaterials(GTItemMaterialTypes.SILVER_PLATE),
	plateBronze = new GTItemMaterials(GTItemMaterialTypes.BRONZE_PLATE),
	plateElectrum = new GTItemMaterials(GTItemMaterialTypes.ELECTRUM_PLATE),
	plateNickel = new GTItemMaterials(GTItemMaterialTypes.NICKEL_PLATE),
	plateInvar = new GTItemMaterials(GTItemMaterialTypes.INVAR_PLATE),
	plateLead = new GTItemMaterials(GTItemMaterialTypes.LEAD_PLATE),
	plateAluminum = new GTItemMaterials(GTItemMaterialTypes.ALUMINUM_PLATE),
	plateChrome = new GTItemMaterials(GTItemMaterialTypes.CHROME_PLATE),
	plateTitanium = new GTItemMaterials(GTItemMaterialTypes.TITANIUM_PLATE),
	plateSteel = new GTItemMaterials(GTItemMaterialTypes.STEEL_PLATE),
	platePlatinum = new GTItemMaterials(GTItemMaterialTypes.PLATINUM_PLATE),
	plateTungsten = new GTItemMaterials(GTItemMaterialTypes.TUNGSTEN_PLATE),
	plateBrass = new GTItemMaterials(GTItemMaterialTypes.BRASS_PLATE),
	plateZinc = new GTItemMaterials(GTItemMaterialTypes.ZINC_PLATE),
	plateTungstensteel = new GTItemMaterials(GTItemMaterialTypes.TUNGSTENSTEEL_PLATE),
	plateOsmium = new GTItemMaterials(GTItemMaterialTypes.OSMIUM_PLATE),
	plateMagnalium = new GTItemMaterials(GTItemMaterialTypes.MAGNALIUM_PLATE),
	flour = new GTItemMaterials(GTItemMaterialTypes.FLOUR),
	plateWood = new GTItemMaterials(GTItemMaterialTypes.WOOD_PLATE);
	
	public static final GTItemNuggets
	nuggetIridium = new GTItemNuggets(GTItemNuggetTypes.IRIDIUM),
	nuggetSilver = new GTItemNuggets(GTItemNuggetTypes.SILVER),
	nuggetAluminum = new GTItemNuggets(GTItemNuggetTypes.ALUMINUM),
	nuggetTitanium = new GTItemNuggets(GTItemNuggetTypes.TITANIUM),
	nuggetChrome = new GTItemNuggets(GTItemNuggetTypes.CHROME),
	nuggetElectrum = new GTItemNuggets(GTItemNuggetTypes.ELECTRUM),
	nuggetTungsten = new GTItemNuggets(GTItemNuggetTypes.TUNGSTEN),
	nuggetLead = new GTItemNuggets(GTItemNuggetTypes.LEAD),
	nuggetZinc = new GTItemNuggets(GTItemNuggetTypes.ZINC),
	nuggetBrass = new GTItemNuggets(GTItemNuggetTypes.BRASS),
	nuggetSteel = new GTItemNuggets(GTItemNuggetTypes.STEEL),
	nuggetPlatinum = new GTItemNuggets(GTItemNuggetTypes.PLATINUM),
	nuggetNickel = new GTItemNuggets(GTItemNuggetTypes.NICKEL),
	nuggetInvar = new GTItemNuggets(GTItemNuggetTypes.INVAR),
	nuggetOsmium = new GTItemNuggets(GTItemNuggetTypes.OSMIUM),
	nuggetCopper = new GTItemNuggets(GTItemNuggetTypes.COPPER),
	nuggetTin = new GTItemNuggets(GTItemNuggetTypes.TIN),
	nuggetBronze = new GTItemNuggets(GTItemNuggetTypes.BRONZE);

	public static final GTItemComponents
	energyFlowCircuit = new GTItemComponents(GTItemComponentTypes.ENERGY_FLOW_CIRCUIT),
	dataControlCircuit = new GTItemComponents(GTItemComponentTypes.DATA_CONTROL_CIRCUIT),
	superConductor = new GTItemComponents(GTItemComponentTypes.SUPERCONDUCTOR),
	dataStorageCircuit = new GTItemComponents(GTItemComponentTypes.DATA_STORAGE_CIRCUIT),
	computerMonitor = new GTItemComponents(GTItemComponentTypes.COMPUTER_MONITOR),
	conveyorModule = new GTItemComponents(GTItemComponentTypes.CONVEYOR_MODULE),
	braintechAerospaceARDT = new GTItemComponents(GTItemComponentTypes.BRAINTECH_AEROSPACE_ARDT),
	diamondSawblade = new GTItemComponents(GTItemComponentTypes.DIAMOND_SAWBLADE),
	diamondGrinder = new GTItemComponents(GTItemComponentTypes.DIAMOND_GRINDER),
	kanthalHeatingCoil = new GTItemComponents(GTItemComponentTypes.KANTHAL_HEATING_COIL),
	nichromeHeatingCoil = new GTItemComponents(GTItemComponentTypes.NICHROME_HEATING_COIL),
	cupronickelHeatingCoil = new GTItemComponents(GTItemComponentTypes.CUPRONICKEL_HEATING_COIL),
	machineParts = new GTItemComponents(GTItemComponentTypes.MACHINE_PARTS),
	wolframiumGrinder = new GTItemComponents(GTItemComponentTypes.WOLFRAMIUM_GRINDER),
	advancedCircuitParts = new GTItemComponents(GTItemComponentTypes.ADVANCED_CIRCUIT_PARTS),
	aluminumMachineHull = new GTItemComponents(GTItemComponentTypes.ALUMINUM_MACHINE_HULL),
	bronzeMachineHull = new GTItemComponents(GTItemComponentTypes.BRONZE_MACHINE_HULL),
	brassMachineHull = new GTItemComponents(GTItemComponentTypes.BRASS_MACHINE_HULL),
	steelMachineHull = new GTItemComponents(GTItemComponentTypes.STEEL_MACHINE_HULL),
	titaniumMachineHull = new GTItemComponents(GTItemComponentTypes.TITANIUM_MACHINE_HULL),
	basicCircuitBoard = new GTItemComponents(GTItemComponentTypes.BASIC_CIRCUIT_BOARD),
	advancedCircuitBoard = new GTItemComponents(GTItemComponentTypes.ADVANCED_CIRCUIT_BOARD),
	eliteCircuitBoard = new GTItemComponents(GTItemComponentTypes.ELITE_CIRCUIT_BOARD);

	public static final Item[] items = {
			creditDoge,
			creditAlk,
			mortarIron,
			mortarFlint,
			hammerIron,
			advancedDrill,
			advancedChainsaw,
			lithiumBattery,
			lapotronicEnergyOrb,
			lithiumBatpack,
			lapotronPack,

			dustEnderpearl,
			dustEnderEye,
			dustLazurite,
			dustPyrite,
			dustCalcite,
			dustSodalite,
			dustNetherrack,
			dustFlint,
			dustSulfur,
			dustSaltpeter,
			dustEndstone,
			dustCinnabar,
			dustMaganese,
			dustMagnesium,
			dustSphalerite,
			dustWoodPulp,
			dustUranium,
			dustBauxite,
			dustAluminum,
			dustTitanium,
			dustChrome,
			dustElectrum,
			dustTungsten,
			dustLead,
			dustZinc,
			dustBrass,
			dustSteel,
			dustPlatinum,
			dustNickel,
			dustInvar,
			dustOsmium,
			dustRuby,
			dustSapphire,
			dustGreenSapphire,
			dustEmerald,
			dustDiamond,
			dustOlivine,
			dustGalena,
			dustPhosphor,
			dustRedGarnet,
			dustYellowGarnet,
			dustPyrope,
			dustAlmandine,
			dustSpessartine,
			dustAndradite,
			dustGrossular,
			dustUvarovite,
			dustAshes,
			dustDarkAshes,
			dustRedRock,
			dustMarble,
			dustBasalt,
			dustThorium,
			dustPlutonium,

			tinyDustEnderpearl,
			tinyDustEnderEye,
			tinyDustLazurite,
			tinyDustPyrite,
			tinyDustCalcite,
			tinyDustSodalite,
			tinyDustNetherrack,
			tinyDustFlint,
			tinyDustSulfur,
			tinyDustSaltpeter,
			tinyDustEndstone,
			tinyDustCinnabar,
			tinyDustMaganese,
			tinyDustMagnesium,
			tinyDustSphalerite,
			tinyDustWoodPulp,
			tinyDustUranium,
			tinyDustBauxite,
			tinyDustAluminum,
			tinyDustTitanium,
			tinyDustChrome,
			tinyDustElectrum,
			tinyDustTungsten,
			tinyDustLead,
			tinyDustZinc,
			tinyDustBrass,
			tinyDustSteel,
			tinyDustPlatinum,
			tinyDustNickel,
			tinyDustInvar,
			tinyDustOsmium,
			tinyDustRuby,
			tinyDustSapphire,
			tinyDustGreenSapphire,
			tinyDustEmerald,
			tinyDustDiamond,
			tinyDustOlivine,
			tinyDustGalena,
			tinyDustPhosphor,
			tinyDustObsidian,
			tinyDustCharcoal,
			tinyDustRedGarnet,
			tinyDustYellowGarnet,
			tinyDustPyrope,
			tinyDustAlmandine,
			tinyDustSpessartine,
			tinyDustAndradite,
			tinyDustGrossular,
			tinyDustUvarovite,
			tinyDustAshes,
			tinyDustDarkAshes,
			tinyDustRedRock,
			tinyDustMarble,
			tinyDustBasalt,
			tinyDustThorium,
			tinyDustPlutonium,
			tinyDustCoal,
			tinyDustIron,
			tinyDustGold,
			tinyDustCopper,
			tinyDustTin,
			tinyDustBronze,
			tinyDustSilver,
			tinyDustClay,
			tinyDustGunpowder,
			tinyDustRedstone,
			tinyDustGlowstone,

			ingotIridiumAlloy,
			ingotHotTungstensteel,
			ingotTungstensteel,
			ingotIridium,
			ingotAluminum,
			ingotTitanium,
			ingotChrome,
			ingotElectrum,
			ingotTungsten,
			ingotLead,
			ingotZinc,
			ingotBrass,
			ingotSteel,
			ingotPlatinum,
			ingotNickel,
			ingotInvar,
			ingotOsmium,
			ruby,
			sapphire,
			greenSapphire,
			lazuriteChunk,
			plateSilicon,
			olivine,
			ingotThorium,
			ingotPlutonium,
			redGarnet,
			yellowGarnet,
			plateIron,
			plateGold,
			plateRefinedIron,
			plateTin,
			plateCopper,
			plateSilver,
			plateBronze,
			plateElectrum,
			plateNickel,
			plateInvar,
			plateLead,
			plateAluminum,
			plateChrome,
			plateTitanium,
			plateSteel,
			platePlatinum,
			plateTungsten,
			plateBrass,
			plateZinc,
			plateTungstensteel,
			plateOsmium,
			plateMagnalium,
			flour,
			plateWood,

			nuggetIridium,
			nuggetSilver,
			nuggetAluminum,
			nuggetTitanium,
			nuggetChrome,
			nuggetElectrum,
			nuggetTungsten,
			nuggetLead,
			nuggetZinc,
			nuggetBrass,
			nuggetSteel,
			nuggetPlatinum,
			nuggetNickel,
			nuggetInvar,
			nuggetOsmium,
			nuggetCopper,
			nuggetTin,
			nuggetBronze,

			energyFlowCircuit,
			dataControlCircuit,
			superConductor,
			dataStorageCircuit,
			computerMonitor,
			conveyorModule,
			braintechAerospaceARDT,
			diamondSawblade,
			diamondGrinder,
			kanthalHeatingCoil,
			nichromeHeatingCoil,
			cupronickelHeatingCoil,
			machineParts,
			wolframiumGrinder,
			advancedCircuitParts,
			aluminumMachineHull,
			bronzeMachineHull,
			brassMachineHull,
			steelMachineHull,
			titaniumMachineHull,
			basicCircuitBoard,
			advancedCircuitBoard,
			eliteCircuitBoard

	};
	@SubscribeEvent
	public static void registerItems(RegistryEvent.Register<Item> event) {
		IForgeRegistry registry = event.getRegistry();
		//items
		GTClassic.logger.info("Registering Items");
		for (Item item : items)
		{
			registry.register(item);
		}
	}
	//inits textures for items
	@SideOnly(Side.CLIENT)
    public static void initModels() {
        creditDoge.initModel();
        creditAlk.initModel();
    }
}
