package gtclassic.util;

import gtclassic.GTClassic;
import gtclassic.items.*;
import gtclassic.items.GTItemComponents.GTItemComponentTypes;
import gtclassic.items.armor.GTItemEnergyPack;
import gtclassic.items.eustorage.GTItemLapotronicEnergyOrb;
import gtclassic.items.eustorage.GTItemLithiumBattery;
import gtclassic.items.resources.GTItemDust;

import gtclassic.items.resources.GTItemNugget;
import gtclassic.items.resources.GTItemTinyDust;
import gtclassic.items.resources.GTItemDust.GTItemDustTypes;
import gtclassic.items.resources.GTItemGem;
import gtclassic.items.resources.GTItemGem.GTItemGemTypes;
import gtclassic.items.resources.GTItemIngot;
import gtclassic.items.resources.GTItemIngot.GTItemIngotTypes;
import gtclassic.items.resources.GTItemNugget.GTItemNuggetTypes;
import gtclassic.items.resources.GTItemPlate;
import gtclassic.items.resources.GTItemPlate.GTItemPlateTypes;
import gtclassic.items.resources.GTItemTinyDust.GTItemTinyDustTypes;
import gtclassic.items.tools.GTItemAdvancedChainsaw;
import gtclassic.items.tools.GTItemAdvancedDrill;
import gtclassic.items.tools.GTItemHammerIron;
import gtclassic.items.tools.GTItemMortar;
import net.minecraft.item.Item;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;
import net.minecraftforge.registries.IForgeRegistry;

public class GTItems {

    public static final GTItemCreditDoge creditDoge = new GTItemCreditDoge();
	public static final GTItemCreditAlk creditAlk = new GTItemCreditAlk();
	public static final GTItemMortar mortarIron = new GTItemMortar(95, "iron_mortar", "mortarIron", 30, true);
	public static final GTItemMortar mortarFlint = new GTItemMortar(7, "flint_mortar", "mortarFlint", 31, false);
	public static final GTItemHammerIron hammerIron = new GTItemHammerIron();
	public static final GTItemAdvancedDrill advancedDrill = new GTItemAdvancedDrill();
	public static final GTItemAdvancedChainsaw advancedChainsaw = new GTItemAdvancedChainsaw();
	public static final GTItemLithiumBattery lithiumBattery = new GTItemLithiumBattery();
	public static final GTItemLapotronicEnergyOrb lapotronicEnergyOrb = new GTItemLapotronicEnergyOrb();
	public static final GTItemEnergyPack lithiumBatpack = new GTItemEnergyPack(58, "gtclassic:textures/models/armor/lithiumbatpack", 600000, "lithium_batpack", ".lithiumBatpack", 1, 200);
	public static final GTItemEnergyPack lapotronPack = new GTItemEnergyPack(45, "gtclassic:textures/models/armor/lapotronpack", 100000000, "lapotron_pack", ".lapotronPack", 3, 1500);
	
	public static final GTItemDust
	dustEnderpearl = new GTItemDust(GTItemDustTypes.ENDERPEARL),
    dustEnderEye = new GTItemDust(GTItemDustTypes.ENDER_EYE),
	dustLazurite = new GTItemDust(GTItemDustTypes.LAZURITE),
	dustPyrite = new GTItemDust(GTItemDustTypes.PYRITE),
	dustCalcite = new GTItemDust(GTItemDustTypes.CALCITE),
	dustSodalite = new GTItemDust(GTItemDustTypes.SODALITE),
	dustNetherrack = new GTItemDust(GTItemDustTypes.NETHERRACK),
	dustFlint = new GTItemDust(GTItemDustTypes.FLINT),
	dustSulfur = new GTItemDust(GTItemDustTypes.SULFUR),
	dustSaltpeter = new GTItemDust(GTItemDustTypes.SALTPETER),
	dustEndstone = new GTItemDust(GTItemDustTypes.ENDSTONE),
	dustCinnabar = new GTItemDust(GTItemDustTypes.CINNABAR),
	dustMaganese = new GTItemDust(GTItemDustTypes.MAGANESE),
	dustMagnesium = new GTItemDust(GTItemDustTypes.MAGNESIUM),
	dustSphalerite = new GTItemDust(GTItemDustTypes.SPHALERITE),
	dustWoodPulp = new GTItemDust(GTItemDustTypes.WOOD_PULP),
	dustUranium = new GTItemDust(GTItemDustTypes.URANIUM),
	dustBauxite = new GTItemDust(GTItemDustTypes.BAUXITE),
	dustAluminum = new GTItemDust(GTItemDustTypes.ALUMINUM),
	dustTitanium = new GTItemDust(GTItemDustTypes.TITANIUM),
	dustChrome = new GTItemDust(GTItemDustTypes.CHROME),
	dustElectrum = new GTItemDust(GTItemDustTypes.ELECTRUM),
	dustTungsten = new GTItemDust(GTItemDustTypes.TUNGSTEN),
	dustLead = new GTItemDust(GTItemDustTypes.LEAD),
	dustZinc = new GTItemDust(GTItemDustTypes.ZINC),
	dustBrass = new GTItemDust(GTItemDustTypes.BRASS),
	dustSteel = new GTItemDust(GTItemDustTypes.STEEL),
	dustPlatinum = new GTItemDust(GTItemDustTypes.PLATINUM),
	dustNickel = new GTItemDust(GTItemDustTypes.NICKEL),
	dustInvar = new GTItemDust(GTItemDustTypes.INVAR),
	dustOsmium = new GTItemDust(GTItemDustTypes.OSMIUM),
	dustRuby = new GTItemDust(GTItemDustTypes.RUBY),
	dustSapphire = new GTItemDust(GTItemDustTypes.SAPPHIRE),
	dustGreenSapphire = new GTItemDust(GTItemDustTypes.GREEN_SAPPHIRE),
	dustEmerald = new GTItemDust(GTItemDustTypes.EMERALD),
	dustDiamond = new GTItemDust(GTItemDustTypes.DIAMOND),
	dustOlivine = new GTItemDust(GTItemDustTypes.OLIVINE),
	dustGalena = new GTItemDust(GTItemDustTypes.GALENA),
	dustPhosphor = new GTItemDust(GTItemDustTypes.PHOSPHOR),
	dustRedGarnet = new GTItemDust(GTItemDustTypes.RED_GARNET),
	dustYellowGarnet = new GTItemDust(GTItemDustTypes.YELLOW_GARNET),
	dustPyrope = new GTItemDust(GTItemDustTypes.PYROPE),
	dustAlmandine = new GTItemDust(GTItemDustTypes.ALMANDINE),
	dustSpessartine = new GTItemDust(GTItemDustTypes.SPESSARTINE),
	dustAndradite = new GTItemDust(GTItemDustTypes.ANDRADITE),
	dustGrossular = new GTItemDust(GTItemDustTypes.GROSSULAR),
	dustUvarovite = new GTItemDust(GTItemDustTypes.UVAROVITE),
	dustAshes = new GTItemDust(GTItemDustTypes.ASHES),
	dustDarkAshes = new GTItemDust(GTItemDustTypes.DARK_ASHES),
	dustRedRock = new GTItemDust(GTItemDustTypes.REDROCK),
	dustMarble = new GTItemDust(GTItemDustTypes.MARBLE),
	dustBasalt = new GTItemDust(GTItemDustTypes.BASALT),
	dustThorium = new GTItemDust(GTItemDustTypes.THORIUM),
	dustPlutonium = new GTItemDust(GTItemDustTypes.PLUTONIUM);

	public static final GTItemTinyDust
	tinyDustEnderpearl = new GTItemTinyDust(GTItemTinyDustTypes.ENDERPEARL),
    tinyDustEnderEye = new GTItemTinyDust(GTItemTinyDustTypes.ENDER_EYE),
	tinyDustLazurite = new GTItemTinyDust(GTItemTinyDustTypes.LAZURITE),
	tinyDustPyrite = new GTItemTinyDust(GTItemTinyDustTypes.PYRITE),
	tinyDustCalcite = new GTItemTinyDust(GTItemTinyDustTypes.CALCITE),
	tinyDustSodalite = new GTItemTinyDust(GTItemTinyDustTypes.SODALITE),
	tinyDustNetherrack = new GTItemTinyDust(GTItemTinyDustTypes.NETHERRACK),
	tinyDustFlint = new GTItemTinyDust(GTItemTinyDustTypes.FLINT),
	tinyDustSulfur = new GTItemTinyDust(GTItemTinyDustTypes.SULFUR),
	tinyDustSaltpeter = new GTItemTinyDust(GTItemTinyDustTypes.SALTPETER),
	tinyDustEndstone = new GTItemTinyDust(GTItemTinyDustTypes.ENDSTONE),
	tinyDustCinnabar = new GTItemTinyDust(GTItemTinyDustTypes.CINNABAR),
	tinyDustMaganese = new GTItemTinyDust(GTItemTinyDustTypes.MAGANESE),
	tinyDustMagnesium = new GTItemTinyDust(GTItemTinyDustTypes.MAGNESIUM),
	tinyDustSphalerite = new GTItemTinyDust(GTItemTinyDustTypes.SPHALERITE),
	tinyDustWoodPulp = new GTItemTinyDust(GTItemTinyDustTypes.WOOD_PULP),
	tinyDustUranium = new GTItemTinyDust(GTItemTinyDustTypes.URANIUM),
	tinyDustBauxite = new GTItemTinyDust(GTItemTinyDustTypes.BAUXITE),
	tinyDustAluminum = new GTItemTinyDust(GTItemTinyDustTypes.ALUMINUM),
	tinyDustTitanium = new GTItemTinyDust(GTItemTinyDustTypes.TITANIUM),
	tinyDustChrome = new GTItemTinyDust(GTItemTinyDustTypes.CHROME),
	tinyDustElectrum = new GTItemTinyDust(GTItemTinyDustTypes.ELECTRUM),
	tinyDustTungsten = new GTItemTinyDust(GTItemTinyDustTypes.TUNGSTEN),
	tinyDustLead = new GTItemTinyDust(GTItemTinyDustTypes.LEAD),
	tinyDustZinc = new GTItemTinyDust(GTItemTinyDustTypes.ZINC),
	tinyDustBrass = new GTItemTinyDust(GTItemTinyDustTypes.BRASS),
	tinyDustSteel = new GTItemTinyDust(GTItemTinyDustTypes.STEEL),
	tinyDustPlatinum = new GTItemTinyDust(GTItemTinyDustTypes.PLATINUM),
	tinyDustNickel = new GTItemTinyDust(GTItemTinyDustTypes.NICKEL),
	tinyDustInvar = new GTItemTinyDust(GTItemTinyDustTypes.INVAR),
	tinyDustOsmium = new GTItemTinyDust(GTItemTinyDustTypes.OSMIUM),
	tinyDustRuby = new GTItemTinyDust(GTItemTinyDustTypes.RUBY),
	tinyDustSapphire = new GTItemTinyDust(GTItemTinyDustTypes.SAPPHIRE),
	tinyDustGreenSapphire = new GTItemTinyDust(GTItemTinyDustTypes.GREEN_SAPPHIRE),
	tinyDustEmerald = new GTItemTinyDust(GTItemTinyDustTypes.EMERALD),
	tinyDustDiamond = new GTItemTinyDust(GTItemTinyDustTypes.DIAMOND),
	tinyDustOlivine = new GTItemTinyDust(GTItemTinyDustTypes.OLIVINE),
	tinyDustGalena = new GTItemTinyDust(GTItemTinyDustTypes.GALENA),
	tinyDustPhosphor = new GTItemTinyDust(GTItemTinyDustTypes.PHOSPHOR),
	tinyDustObsidian = new GTItemTinyDust(GTItemTinyDustTypes.OBSIDIAN),
	tinyDustCharcoal = new GTItemTinyDust(GTItemTinyDustTypes.CHARCOAL),
	tinyDustRedGarnet = new GTItemTinyDust(GTItemTinyDustTypes.RED_GARNET),
	tinyDustYellowGarnet = new GTItemTinyDust(GTItemTinyDustTypes.YELLOW_GARNET),
	tinyDustPyrope = new GTItemTinyDust(GTItemTinyDustTypes.PYROPE),
	tinyDustAlmandine = new GTItemTinyDust(GTItemTinyDustTypes.ALMANDINE),
	tinyDustSpessartine = new GTItemTinyDust(GTItemTinyDustTypes.SPESSARTINE),
	tinyDustAndradite = new GTItemTinyDust(GTItemTinyDustTypes.ANDRADITE),
	tinyDustGrossular = new GTItemTinyDust(GTItemTinyDustTypes.GROSSULAR),
	tinyDustUvarovite = new GTItemTinyDust(GTItemTinyDustTypes.UVAROVITE),
	tinyDustAshes = new GTItemTinyDust(GTItemTinyDustTypes.ASHES),
	tinyDustDarkAshes = new GTItemTinyDust(GTItemTinyDustTypes.DARK_ASHES),
	tinyDustRedRock = new GTItemTinyDust(GTItemTinyDustTypes.REDROCK),
	tinyDustMarble = new GTItemTinyDust(GTItemTinyDustTypes.MARBLE),
	tinyDustBasalt = new GTItemTinyDust(GTItemTinyDustTypes.BASALT),
	tinyDustThorium = new GTItemTinyDust(GTItemTinyDustTypes.THORIUM),
	tinyDustPlutonium = new GTItemTinyDust(GTItemTinyDustTypes.PLUTONIUM),
	tinyDustCoal = new GTItemTinyDust(GTItemTinyDustTypes.COAL),
	tinyDustIron = new GTItemTinyDust(GTItemTinyDustTypes.IRON),
	tinyDustGold = new GTItemTinyDust(GTItemTinyDustTypes.GOLD),
	tinyDustCopper = new GTItemTinyDust(GTItemTinyDustTypes.COPPER),
	tinyDustTin = new GTItemTinyDust(GTItemTinyDustTypes.TIN),
	tinyDustBronze = new GTItemTinyDust(GTItemTinyDustTypes.BRONZE),
	tinyDustSilver = new GTItemTinyDust(GTItemTinyDustTypes.SILVER),
	tinyDustClay = new GTItemTinyDust(GTItemTinyDustTypes.CLAY),
	tinyDustGunpowder = new GTItemTinyDust(GTItemTinyDustTypes.GUNPOWDER),
	tinyDustRedstone = new GTItemTinyDust(GTItemTinyDustTypes.REDSTONE),
	tinyDustGlowstone = new GTItemTinyDust(GTItemTinyDustTypes.GLOWSTONE);

	public static final GTItemIngot
	ingotIridiumAlloy = new GTItemIngot(GTItemIngotTypes.IRIDIUM_ALLOY),
	ingotHotTungstensteel = new GTItemIngot(GTItemIngotTypes.HOT_TUNGSTENSTEEL),
	ingotTungstensteel = new GTItemIngot(GTItemIngotTypes.TUNGSTENSTEEL),
	ingotIridium = new GTItemIngot(GTItemIngotTypes.IRIDIUM),
	ingotAluminum = new GTItemIngot(GTItemIngotTypes.ALUMINUM),
	ingotTitanium = new GTItemIngot(GTItemIngotTypes.TITANIUM),
	ingotTungsten = new GTItemIngot(GTItemIngotTypes.TUNGSTEN),
	ingotChrome = new GTItemIngot(GTItemIngotTypes.CHROME),
	ingotElectrum = new GTItemIngot(GTItemIngotTypes.ELECTRUM),
	ingotLead = new GTItemIngot(GTItemIngotTypes.LEAD),
	ingotZinc = new GTItemIngot(GTItemIngotTypes.ZINC),
	ingotBrass = new GTItemIngot(GTItemIngotTypes.BRASS),
	ingotSteel = new GTItemIngot(GTItemIngotTypes.STEEL),
	ingotPlatinum = new GTItemIngot(GTItemIngotTypes.PLATINUM),
	ingotNickel = new GTItemIngot(GTItemIngotTypes.NICKEL),
	ingotInvar = new GTItemIngot(GTItemIngotTypes.INVAR),
	ingotOsmium = new GTItemIngot(GTItemIngotTypes.OSMIUM),
	ingotThorium = new GTItemIngot(GTItemIngotTypes.THORIUM),
	ingotPlutonium = new GTItemIngot(GTItemIngotTypes.PLUTONIUM);
	
	public static final GTItemGem
	ruby = new GTItemGem(GTItemGemTypes.RUBY),
	sapphire = new GTItemGem(GTItemGemTypes.SAPPHIRE),
	greenSapphire = new GTItemGem(GTItemGemTypes.GREEN_SAPPHIRE),
	olivine = new GTItemGem(GTItemGemTypes.OLIVINE),
	redGarnet = new GTItemGem(GTItemGemTypes.RED_GARNET),
	yellowGarnet = new GTItemGem(GTItemGemTypes.YELLOW_GARNET);
	
	public static final GTItemPlate
	plateLazurite = new GTItemPlate(GTItemPlateTypes.LAZURITE),
	plateSilicon = new GTItemPlate(GTItemPlateTypes.SILICON),
	plateIron = new GTItemPlate(GTItemPlateTypes.IRON),
	plateGold = new GTItemPlate(GTItemPlateTypes.GOLD),
	plateRefinedIron = new GTItemPlate(GTItemPlateTypes.REFINED_IRON),
	plateTin = new GTItemPlate(GTItemPlateTypes.TIN),
	plateCopper = new GTItemPlate(GTItemPlateTypes.COPPER),
	plateSilver = new GTItemPlate(GTItemPlateTypes.SILVER),
	plateBronze = new GTItemPlate(GTItemPlateTypes.BRONZE),
	plateElectrum = new GTItemPlate(GTItemPlateTypes.ELECTRUM),
	plateNickel = new GTItemPlate(GTItemPlateTypes.NICKEL),
	plateInvar = new GTItemPlate(GTItemPlateTypes.INVAR),
	plateLead = new GTItemPlate(GTItemPlateTypes.LEAD),
	plateAluminum = new GTItemPlate(GTItemPlateTypes.ALUMINUM),
	plateChrome = new GTItemPlate(GTItemPlateTypes.CHROME),
	plateTitanium = new GTItemPlate(GTItemPlateTypes.TITANIUM),
	plateSteel = new GTItemPlate(GTItemPlateTypes.STEEL),
	platePlatinum = new GTItemPlate(GTItemPlateTypes.PLATINUM),
	plateTungsten = new GTItemPlate(GTItemPlateTypes.TUNGSTEN),
	plateBrass = new GTItemPlate(GTItemPlateTypes.BRASS),
	plateZinc = new GTItemPlate(GTItemPlateTypes.ZINC),
	plateTungstensteel = new GTItemPlate(GTItemPlateTypes.TUNGSTENSTEEL),
	plateOsmium = new GTItemPlate(GTItemPlateTypes.OSMIUM),
	plateMagnalium = new GTItemPlate(GTItemPlateTypes.MAGNALIUM),
	plateWood = new GTItemPlate(GTItemPlateTypes.WOOD);
	
	public static final GTItemNugget
	nuggetIridium = new GTItemNugget(GTItemNuggetTypes.IRIDIUM),
	nuggetSilver = new GTItemNugget(GTItemNuggetTypes.SILVER),
	nuggetAluminum = new GTItemNugget(GTItemNuggetTypes.ALUMINUM),
	nuggetTitanium = new GTItemNugget(GTItemNuggetTypes.TITANIUM),
	nuggetChrome = new GTItemNugget(GTItemNuggetTypes.CHROME),
	nuggetElectrum = new GTItemNugget(GTItemNuggetTypes.ELECTRUM),
	nuggetTungsten = new GTItemNugget(GTItemNuggetTypes.TUNGSTEN),
	nuggetLead = new GTItemNugget(GTItemNuggetTypes.LEAD),
	nuggetZinc = new GTItemNugget(GTItemNuggetTypes.ZINC),
	nuggetBrass = new GTItemNugget(GTItemNuggetTypes.BRASS),
	nuggetSteel = new GTItemNugget(GTItemNuggetTypes.STEEL),
	nuggetPlatinum = new GTItemNugget(GTItemNuggetTypes.PLATINUM),
	nuggetNickel = new GTItemNugget(GTItemNuggetTypes.NICKEL),
	nuggetInvar = new GTItemNugget(GTItemNuggetTypes.INVAR),
	nuggetOsmium = new GTItemNugget(GTItemNuggetTypes.OSMIUM),
	nuggetCopper = new GTItemNugget(GTItemNuggetTypes.COPPER),
	nuggetTin = new GTItemNugget(GTItemNuggetTypes.TIN),
	nuggetBronze = new GTItemNugget(GTItemNuggetTypes.BRONZE);

	public static final GTItemComponents
	energyFlowCircuit = new GTItemComponents(GTItemComponentTypes.ENERGY_FLOW_CIRCUIT),
	dataControlCircuit = new GTItemComponents(GTItemComponentTypes.DATA_CONTROL_CIRCUIT),
	superConductor = new GTItemComponents(GTItemComponentTypes.SUPERCONDUCTOR),
	dataStorageCircuit = new GTItemComponents(GTItemComponentTypes.DATA_STORAGE_CIRCUIT),
	computerMonitor = new GTItemComponents(GTItemComponentTypes.COMPUTER_MONITOR),
	conveyorModule = new GTItemComponents(GTItemComponentTypes.CONVEYOR_MODULE),
	braintechAerospaceARDT = new GTItemComponents(GTItemComponentTypes.BRAINTECH_AEROSPACE_ARDT),
	diamondSawblade = new GTItemComponents(GTItemComponentTypes.DIAMOND_SAWBLADE),
	diamondGrinder = new GTItemComponents(GTItemComponentTypes.DIAMOND_GRINDER),
	kanthalHeatingCoil = new GTItemComponents(GTItemComponentTypes.KANTHAL_HEATING_COIL),
	nichromeHeatingCoil = new GTItemComponents(GTItemComponentTypes.NICHROME_HEATING_COIL),
	cupronickelHeatingCoil = new GTItemComponents(GTItemComponentTypes.CUPRONICKEL_HEATING_COIL),
	machineParts = new GTItemComponents(GTItemComponentTypes.MACHINE_PARTS),
	wolframiumGrinder = new GTItemComponents(GTItemComponentTypes.WOLFRAMIUM_GRINDER),
	advancedCircuitParts = new GTItemComponents(GTItemComponentTypes.ADVANCED_CIRCUIT_PARTS),
	aluminumMachineHull = new GTItemComponents(GTItemComponentTypes.ALUMINUM_MACHINE_HULL),
	bronzeMachineHull = new GTItemComponents(GTItemComponentTypes.BRONZE_MACHINE_HULL),
	brassMachineHull = new GTItemComponents(GTItemComponentTypes.BRASS_MACHINE_HULL),
	steelMachineHull = new GTItemComponents(GTItemComponentTypes.STEEL_MACHINE_HULL),
	titaniumMachineHull = new GTItemComponents(GTItemComponentTypes.TITANIUM_MACHINE_HULL),
	basicCircuitBoard = new GTItemComponents(GTItemComponentTypes.BASIC_CIRCUIT_BOARD),
	advancedCircuitBoard = new GTItemComponents(GTItemComponentTypes.ADVANCED_CIRCUIT_BOARD),
	eliteCircuitBoard = new GTItemComponents(GTItemComponentTypes.ELITE_CIRCUIT_BOARD);

	public static final Item[] items = {
			creditDoge,
			creditAlk,
			mortarIron,
			mortarFlint,
			hammerIron,
			advancedDrill,
			advancedChainsaw,
			lithiumBattery,
			lapotronicEnergyOrb,
			lithiumBatpack,
			lapotronPack,

			dustEnderpearl,
			dustEnderEye,
			dustLazurite,
			dustPyrite,
			dustCalcite,
			dustSodalite,
			dustNetherrack,
			dustFlint,
			dustSulfur,
			dustSaltpeter,
			dustEndstone,
			dustCinnabar,
			dustMaganese,
			dustMagnesium,
			dustSphalerite,
			dustWoodPulp,
			dustUranium,
			dustBauxite,
			dustAluminum,
			dustTitanium,
			dustChrome,
			dustElectrum,
			dustTungsten,
			dustLead,
			dustZinc,
			dustBrass,
			dustSteel,
			dustPlatinum,
			dustNickel,
			dustInvar,
			dustOsmium,
			dustRuby,
			dustSapphire,
			dustGreenSapphire,
			dustEmerald,
			dustDiamond,
			dustOlivine,
			dustGalena,
			dustPhosphor,
			dustRedGarnet,
			dustYellowGarnet,
			dustPyrope,
			dustAlmandine,
			dustSpessartine,
			dustAndradite,
			dustGrossular,
			dustUvarovite,
			dustAshes,
			dustDarkAshes,
			dustRedRock,
			dustMarble,
			dustBasalt,
			dustThorium,
			dustPlutonium,

			tinyDustEnderpearl,
			tinyDustEnderEye,
			tinyDustLazurite,
			tinyDustPyrite,
			tinyDustCalcite,
			tinyDustSodalite,
			tinyDustNetherrack,
			tinyDustFlint,
			tinyDustSulfur,
			tinyDustSaltpeter,
			tinyDustEndstone,
			tinyDustCinnabar,
			tinyDustMaganese,
			tinyDustMagnesium,
			tinyDustSphalerite,
			tinyDustWoodPulp,
			tinyDustUranium,
			tinyDustBauxite,
			tinyDustAluminum,
			tinyDustTitanium,
			tinyDustChrome,
			tinyDustElectrum,
			tinyDustTungsten,
			tinyDustLead,
			tinyDustZinc,
			tinyDustBrass,
			tinyDustSteel,
			tinyDustPlatinum,
			tinyDustNickel,
			tinyDustInvar,
			tinyDustOsmium,
			tinyDustRuby,
			tinyDustSapphire,
			tinyDustGreenSapphire,
			tinyDustEmerald,
			tinyDustDiamond,
			tinyDustOlivine,
			tinyDustGalena,
			tinyDustPhosphor,
			tinyDustObsidian,
			tinyDustCharcoal,
			tinyDustRedGarnet,
			tinyDustYellowGarnet,
			tinyDustPyrope,
			tinyDustAlmandine,
			tinyDustSpessartine,
			tinyDustAndradite,
			tinyDustGrossular,
			tinyDustUvarovite,
			tinyDustAshes,
			tinyDustDarkAshes,
			tinyDustRedRock,
			tinyDustMarble,
			tinyDustBasalt,
			tinyDustThorium,
			tinyDustPlutonium,
			tinyDustCoal,
			tinyDustIron,
			tinyDustGold,
			tinyDustCopper,
			tinyDustTin,
			tinyDustBronze,
			tinyDustSilver,
			tinyDustClay,
			tinyDustGunpowder,
			tinyDustRedstone,
			tinyDustGlowstone,

			ingotIridiumAlloy,
			ingotHotTungstensteel,
			ingotTungstensteel,
			ingotIridium,
			ingotAluminum,
			ingotTitanium,
			ingotChrome,
			ingotElectrum,
			ingotTungsten,
			ingotLead,
			ingotZinc,
			ingotBrass,
			ingotSteel,
			ingotPlatinum,
			ingotNickel,
			ingotInvar,
			ingotOsmium,
			ingotThorium,
			ingotPlutonium,
			
			ruby,
			sapphire,
			greenSapphire,
			olivine,
			redGarnet,
			yellowGarnet,
			
			plateLazurite,
			plateSilicon,
			plateIron,
			plateGold,
			plateRefinedIron,
			plateTin,
			plateCopper,
			plateSilver,
			plateBronze,
			plateElectrum,
			plateNickel,
			plateInvar,
			plateLead,
			plateAluminum,
			plateChrome,
			plateTitanium,
			plateSteel,
			platePlatinum,
			plateTungsten,
			plateBrass,
			plateZinc,
			plateTungstensteel,
			plateOsmium,
			plateMagnalium,
			plateWood,

			nuggetIridium,
			nuggetSilver,
			nuggetAluminum,
			nuggetTitanium,
			nuggetChrome,
			nuggetElectrum,
			nuggetTungsten,
			nuggetLead,
			nuggetZinc,
			nuggetBrass,
			nuggetSteel,
			nuggetPlatinum,
			nuggetNickel,
			nuggetInvar,
			nuggetOsmium,
			nuggetCopper,
			nuggetTin,
			nuggetBronze,

			energyFlowCircuit,
			dataControlCircuit,
			superConductor,
			dataStorageCircuit,
			computerMonitor,
			conveyorModule,
			braintechAerospaceARDT,
			diamondSawblade,
			diamondGrinder,
			kanthalHeatingCoil,
			nichromeHeatingCoil,
			cupronickelHeatingCoil,
			machineParts,
			wolframiumGrinder,
			advancedCircuitParts,
			aluminumMachineHull,
			bronzeMachineHull,
			brassMachineHull,
			steelMachineHull,
			titaniumMachineHull,
			basicCircuitBoard,
			advancedCircuitBoard,
			eliteCircuitBoard

	};
	@SubscribeEvent
	public static void registerItems(RegistryEvent.Register<Item> event) {
		IForgeRegistry registry = event.getRegistry();
		//items
		GTClassic.logger.info("Registering Items");
		for (Item item : items)
		{
			registry.register(item);
		}
	}
	//inits textures for items
	@SideOnly(Side.CLIENT)
    public static void initModels() {
        creditDoge.initModel();
        creditAlk.initModel();
    }
}
